/*
contains the new endpoint:

POST /users should create a new user in DB:

  - To create a user, you must specify an email and a password
  - If the email is missing, return an error Missing email with a status code 400
  - If the password is missing, return an error Missing password with a status code 400
  - If the email already exists in DB, return an error Already exist with a status code 400
  - The password must be stored after being hashed in SHA1
  - The endpoint is returning the new user with only the email and the id
  (auto generated by MongoDB) with a status code 201
  - The new user must be saved in the collection users:
    - email: same as the value received
    - password: SHA1 value of the value received

add a new endpoint:

GET /users/me should retrieve the user base on the token used:

  - Retrieve the user based on the token:
    - If not found, return an error Unauthorized with a status code 401
    - Otherwise, return the user object (email and id only)

*/

import sha1 from 'sha1';
import Queue from 'bull';
import { ObjectId } from 'mongodb';
import dbClient from '../utils/db';
import getIdAndKey from '../utils/users';

const userQ = new Queue('userQ');

class UsersController {
  static async postNew(req, res) {
    const { email, password } = req.body;

    if (!email) return res.status(400).send({ error: 'Missing email' });
    if (!password) return res.status(400).send({ error: 'Missing password' });
    const existEmail = await dbClient.users.findOne({ email });
    if (existEmail) return res.status(400).send({ error: 'Already exist' });

    const hashPass = sha1(password);

    const insertStat = await dbClient.users.insertOne({
      email,
      password: hashPass,
    });

    const createdUser = {
      id: insertStat.insertedId,
      email,
    };

    await userQ.add({
      userId: insertStat.insertedId.toString(),
    });

    return res.status(201).send(createdUser);
  }

  static async getMe(req, res) {
    const { userId } = await getIdAndKey(req);

    const user = await dbClient.users.findOne({ _id: ObjectId(userId) });
    if (!user) return res.status(401).send({ error: 'Unauthorized' });

    const userInfo = { id: user._id, ...user };
    delete userInfo._id;
    delete userInfo.password;

    return res.status(200).send(userInfo);
  }
}

export default UsersController;
